######################################################################
# Automatically generated by qmake (3.0) ?? 8? 17 13:57:39 2017
######################################################################

TEMPLATE = app
TARGET = qt-console
INCLUDEPATH += .
QT += network core gui

# Input
QMAKE_CXXFLAGS += -std=c++11
HEADERS += ClientDecoder.h MessageDef.h TRMSConsole.h Utils.h
SOURCES += ClientDecoder.cpp main.cpp TRMSConsole.cpp Utils.cpp
