######################################################################
# Automatically generated by qmake (3.0) ?? 8? 19 11:21:10 2017
######################################################################

TEMPLATE = app
TARGET = qt-console
INCLUDEPATH += .

QT += core network
CONFIG += c++11

# Input
HEADERS += p_TabStruct.h TRMSConsole.h Utils.h
SOURCES += main.cpp TRMSConsole.cpp Utils.cpp
